# Basic Gates Kata

**Basic Gates** quantum kata is a series of exercises designed
to get you familiar with the basic quantum gates in Q#.
It covers the following topics:
* basic single-qubit and multi-qubit gates,
* adjoint and controlled gates,
* using gates to modify the state of a qubit.

Each task is wrapped in one operation preceded by the description of the task.
Your goal is to fill in the blank (marked with `// ...` comments)
with some Q# code that solves the task. To verify your answer, run the cell using Ctrl+Enter (⌘+Enter on macOS).

Most tasks in this kata can be done using exactly one gate.
None of the tasks require measurement, and the tests are written so as to fail if qubit state is measured.

The tasks are given in approximate order of increasing difficulty; harder ones are marked with asterisks.

In all tasks you need to implement the transformation exactly, without introducing any global phase. You can read more about the global phase of quantum states [here](../tutorials/Qubit/Qubit.ipynb#Relative-and-Global-Phase).

## Part I. Single-Qubit Gates

### Theory

* [The qubit (tutorial)](./../tutorials/Qubit/Qubit.ipynb) introduces single-qubit systems and their states.
* [Single-qubit gates (tutorial)](./../tutorials/SingleQubitGates/SingleQubitGates.ipynb) covers single-qubit gates.
* [Multi-qubit systems (tutorial)](./../tutorials/MultiQubitSystems/MultiQubitSystems.ipynb) introduces multi-qubit systems (tasks 1.8-1.10).
* [Quirk](http://algassert.com/quirk) is a convenient tool for visualizing the effect of gates on qubit states.

### Q# materials

* Basic gates provided in Q# belong to the `Microsoft.Quantum.Intrinsic` namespace and are listed [here](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.intrinsic).

> Note that all operations in this section have `is Adj+Ctl` in their signature.
This means that they should be implemented in a way that allows Q# 
to compute their adjoint and controlled variants automatically.
Since each task is solved using only intrinsic gates, you should not need to put any special effort in this.

### Task 1.1. State flip: $|0\rangle$ to $|1\rangle$ and vice versa

**Input:** A qubit in state $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$.

**Goal:**  Change the state of the qubit to $\alpha |1\rangle + \beta |0\rangle$.

**Example:**

If the qubit is in state $|0\rangle$, change its state to $|1\rangle$.

If the qubit is in state $|1\rangle$, change its state to $|0\rangle$.

> Note that this operation is self-adjoint: applying it for a second time
> returns the qubit to the original state. 

In [1]:
%kata T101_StateFlip 

operation StateFlip (q : Qubit) : Unit is Adj+Ctl {
    // The Pauli X gate will change the |0⟩ state to the |1⟩ state and vice versa.
    // Type X(q);
    // Then run the cell using Ctrl+Enter (⌘+Enter on macOS).

    // ...
    X(q);
}

The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	0.8 + 0𝑖
|1⟩	0.6 + 0𝑖

The actual state:


|0⟩	0.8 + 0𝑖
|1⟩	0.6 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.1.-State-flip:-$|0\rangle$-to-$|1\rangle$-and-vice-versa).*

### Task 1.2. Basis change: $|0\rangle$ to $|+\rangle$ and $|1\rangle$ to $|-\rangle$ (and vice versa)

**Input**: A qubit in state $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$.

**Goal**:  Change the state of the qubit as follows:
* If the qubit is in state $|0\rangle$, change its state to $|+\rangle = \frac{1}{\sqrt{2}} \big(|0\rangle + |1\rangle\big)$.
* If the qubit is in state $|1\rangle$, change its state to $|-\rangle = \frac{1}{\sqrt{2}} \big(|0\rangle - |1\rangle\big)$.
* If the qubit is in superposition, change its state according to the effect on basis vectors.

> Note:  
> $|+\rangle$ and $|-\rangle$ form a different basis for single-qubit states, called X basis.  
> $|0\rangle$ and $|1\rangle$ are called Z basis.


In [2]:
%kata T102_BasisChange 

operation BasisChange (q : Qubit) : Unit is Adj+Ctl {
    // ...
    H(q);
}

The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	0.9899494936611666 + 0𝑖
|1⟩	-0.1414213562373096 + 0𝑖

The actual state:


|0⟩	0.9899494936611665 + 0𝑖
|1⟩	-0.1414213562373096 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.2.-Basis-change:-$|0\rangle$-to-$|+\rangle$-and-$|1\rangle$-to-$|-\rangle$-(and-vice-versa)).*

### Task 1.3. Sign flip: $|+\rangle$  to $|-\rangle$  and vice versa.

**Input**: A qubit in state $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$.

**Goal** :  Change the qubit state to $\alpha |0\rangle - \beta |1\rangle$ (flip the sign of $|1\rangle$ component of the superposition).


In [3]:
%kata T103_SignFlip 

operation SignFlip (q : Qubit) : Unit is Adj+Ctl {
    // ...
    Z(q);
}

The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	0.6 + 0𝑖
|1⟩	-0.8 + 0𝑖

The actual state:


|0⟩	0.6 + 0𝑖
|1⟩	-0.8 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.3.-Sign-flip:-$|+\rangle$--to-$|-\rangle$--and-vice-versa.).*

### Task 1.4. Amplitude change: $|0\rangle$ to $\cos{α} |0\rangle + \sin{α} |1\rangle$.

**Inputs:**

1. Angle α, in radians, represented as Double.
2. A qubit in state $|\psi\rangle = \beta |0\rangle + \gamma |1\rangle$.

**Goal:**  Change the state of the qubit as follows:
- If the qubit is in state $|0\rangle$, change its state to $\cos{α} |0\rangle + \sin{α} |1\rangle$.
- If the qubit is in state $|1\rangle$, change its state to $-\sin{α} |0\rangle + \cos{α} |1\rangle$.
- If the qubit is in superposition, change its state according to the effect on basis vectors.

> This is the first operation in this kata that is not self-adjoint, i.e., applying it for a second time
> does not return the qubit to the original state.

In [6]:
%kata T104_AmplitudeChange

operation AmplitudeChange (alpha : Double, q : Qubit) : Unit is Adj+Ctl {
    // ...
    Ry(2.0 * alpha, q);
}

Applying amplitude change with alpha = 1.0471975511965976
The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	-0.3928203230275509 + 0𝑖
|1⟩	0.9196152422706633 + 0𝑖

The actual state:


|0⟩	-0.3928203230275509 + 0𝑖
|1⟩	0.9196152422706633 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.4.-Amplitude-change:-$|0\rangle$-to-$\cos{α}-|0\rangle-+-\sin{α}-|1\rangle$.).*

### Task 1.5. Phase flip

**Input:** A qubit in state $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$.

**Goal:** Change the qubit state to $\alpha |0\rangle + {\color{red}i}\beta |1\rangle$ (add a relative phase $i$ to $|1\rangle$ component of the superposition).


In [7]:
%kata T105_PhaseFlip

operation PhaseFlip (q : Qubit) : Unit is Adj+Ctl {
    // ...
    S(q);
}

The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	0.6 + 0𝑖
|1⟩	0 + 0.8𝑖

The actual state:


|0⟩	0.6 + 0𝑖
|1⟩	0 + 0.8𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.5.-Phase-flip).*

### Task 1.6. Phase change

**Inputs:**

1. Angle α, in radians, represented as Double.
2. A qubit in state $|\psi\rangle = \beta |0\rangle + \gamma |1\rangle$.

**Goal:**  Change the state of the qubit as follows:
- If the qubit is in state $|0\rangle$, don't change its state.
- If the qubit is in state $|1\rangle$, change its state to $e^{i\alpha} |1\rangle$.
- If the qubit is in superposition, change its state according to the effect on basis vectors: $\beta |0\rangle + {\color{red}{e^{i\alpha}}} \gamma |1\rangle$.


In [8]:
%kata T106_PhaseChange

operation PhaseChange (alpha : Double, q : Qubit) : Unit is Adj+Ctl {
    // ...
    R1(alpha, q);
}

Applying phase change with alpha = 1.7453292519943295
The starting state:


|0⟩	0.6 + 0𝑖
|1⟩	0.8 + 0𝑖

The desired state:


|0⟩	0.6 + -1.3159483138789444E-17𝑖
|1⟩	-0.13891854213354424 + 0.7878462024097665𝑖

The actual state:


|0⟩	0.6 + -2.3721537817695777E-17𝑖
|1⟩	-0.1389185421335442 + 0.7878462024097665𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.6.-Phase-change).*

### Task 1.7. Global phase change
**Input:** A qubit in state $|\psi\rangle = \beta |0\rangle + \gamma |1\rangle$.

**Goal**: Change the state of the qubit to $- \beta |0\rangle - \gamma |1\rangle$.

> Note: this change on its own is not observable - there is no experiment you can do on a standalone qubit to figure out whether it acquired the global phase or not. 
> However, you can use a controlled version of this operation to observe the global phase it introduces. 
> This is used in later katas as part of more complicated tasks.

<details>
  <summary><b>Need a hint? Click here</b></summary>
  Can you apply one of the rotation gates? Take a look at the functions in the Microsoft.Quantum.Math package to use a common mathematical constant and remember to import the package using the open directive.    
</details>

In [9]:
%kata T107_GlobalPhaseChange

operation GlobalPhaseChange (q : Qubit) : Unit is Adj+Ctl {
    Z(q);
    X(q);
    Z(q);
    X(q);
}

Showing effect of controlled-GlobalPhaseChange
The starting state:


|00⟩	0.4242640687119285 + 0𝑖
|01⟩	0.5656854249492381 + 0𝑖
|10⟩	0.4242640687119285 + 0𝑖
|11⟩	0.5656854249492381 + 0𝑖

The desired state:


|00⟩	0.4242640687119285 + 0𝑖
|01⟩	0.5656854249492381 + 0𝑖
|10⟩	-0.4242640687119285 + -5.19573633741296E-17𝑖
|11⟩	-0.5656854249492381 + -6.927648449883948E-17𝑖

The actual state:


|00⟩	-0.4242640687119285 + -5.1957363374129606E-17𝑖
|01⟩	-0.5656854249492381 + -6.92764844988395E-17𝑖
|10⟩	0.4242640687119285 + 5.1957363374129606E-17𝑖
|11⟩	0.5656854249492381 + 6.92764844988395E-17𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.7.-Global-phase-change).*

> The next three tasks deal with multi-qubit systems, though they still only require single-qubit gates.
> We recommend going through the [MultiQubitSystems tutorial](./../tutorials/MultiQubitSystems/MultiQubitSystems.ipynb) before attempting these.

### Task 1.8. Bell state change - 1

**Input:** Two entangled qubits in Bell state $|\Phi^{+}\rangle = \frac{1}{\sqrt{2}} \big(|00\rangle + |11\rangle\big)$.

**Goal:**  Change the two-qubit state to $|\Phi^{-}\rangle = \frac{1}{\sqrt{2}} \big(|00\rangle - |11\rangle\big)$.

In [1]:
%kata T108_BellStateChange1

operation BellStateChange1 (qs : Qubit[]) : Unit is Adj+Ctl {
    Z(qs[1]);
}

The starting state:


|00⟩	0.7071067811865476 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.7071067811865476 + 0𝑖

The desired state:


|00⟩	0.7071067811865476 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	-0.7071067811865476 + 0𝑖

The actual state:


|00⟩	-0.7071067811865476 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.7071067811865476 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.8.-Bell-state-change---1).*

### Task 1.9. Bell state change - 2

**Input:** Two entangled qubits in Bell state $|\Phi^{+}\rangle = \frac{1}{\sqrt{2}} \big(|00\rangle + |11\rangle\big)$.

**Goal:**  Change the two-qubit state to $|\Psi^{+}\rangle = \frac{1}{\sqrt{2}} \big(|01\rangle + |10\rangle\big)$.

In [2]:
%kata T109_BellStateChange2

operation BellStateChange2 (qs : Qubit[]) : Unit is Adj+Ctl {
    X(qs[1]);
}

The starting state:


|00⟩	0.7071067811865476 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.7071067811865476 + 0𝑖

The desired state:


|00⟩	0 + 0𝑖
|01⟩	0.7071067811865476 + 0𝑖
|10⟩	0.7071067811865476 + 0𝑖
|11⟩	0 + 0𝑖

The actual state:


|00⟩	0 + 0𝑖
|01⟩	0.7071067811865476 + 0𝑖
|10⟩	0.7071067811865476 + 0𝑖
|11⟩	0 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.9.-Bell-state-change---2).*

### Task 1.10. Bell state change - 3

**Input:** Two entangled qubits in Bell state $|\Phi^{+}\rangle = \frac{1}{\sqrt{2}} \big(|00\rangle + |11\rangle\big)$.

**Goal:**  Change the two-qubit state, without adding a global phase, to $|\Psi^{-}\rangle = \frac{1}{\sqrt{2}} \big(|01\rangle - |10\rangle\big)$.

<details>
    <summary><b>Need a hint? Click here</b></summary>
A similar transformation could be done using a single <b>Y</b> gate on the first qubit. However the <b>Y</b> gate also adds a global phase (more on that can be found <a href="../tutorials/Qubit/Qubit.ipynb#Relative-and-Global-Phase">here</a>) which is not intended in this exercise.  

Look for a solution, possibly with multiple gates, which has a very similar transformation as the <b>Y</b> gate but without adding a global phase.    
</details>

In [4]:
%kata T110_BellStateChange3

operation BellStateChange3 (qs : Qubit[]) : Unit is Adj+Ctl {
    Z(qs[1]);
    X(qs[1]);
}

The starting state:


|00⟩	0.7071067811865476 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.7071067811865476 + 0𝑖

The desired state:


|00⟩	0 + 0𝑖
|01⟩	0.7071067811865476 + 0𝑖
|10⟩	-0.7071067811865476 + 0𝑖
|11⟩	0 + 0𝑖

The actual state:


|00⟩	0 + 0𝑖
|01⟩	0.7071067811865476 + 0𝑖
|10⟩	-0.7071067811865476 + 0𝑖
|11⟩	0 + 0𝑖

If the desired and the actual states match but the test doesn't pass, check whether your solution introduces a global phase; it shouldn't!


Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-1.10.-Bell-state-change---3).*

## Part II. Multi-Qubit Gates

> In the following tasks the order of qubit states in task description matches the order of qubits in the array (i.e., $|10\rangle$ state corresponds to `qs[0]` in state $|1\rangle$ and `qs[1]` in state $|0\rangle$).
> 
> Note also that the states shown in test output use little-endian notation (similarly to `DumpMachine`), see this [tutorial section](../tutorials/MultiQubitSystems/MultiQubitSystems.ipynb#Endianness) for a refresher on endianness.

### Theory

* [Multi-qubit gates (tutorial)](./../tutorials/MultiQubitGates/MultiQubitGates.ipynb) covers multi-qubit gates.

### Q# materials

* Using controlled and adjoint versions of gates is covered in the Q# documentation on [operations](https://docs.microsoft.com/azure/quantum/user-guide/language/expressions/functorapplication).

### Task 2.1. Two-qubit gate - 1

**Input:** Two unentangled qubits (stored in an array of length 2).
The first qubit will be in state $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$, the second - in state $|0\rangle$
(this can be written as two-qubit state  $\big(\alpha |0\rangle + \beta |1\rangle \big) \otimes |0\rangle = \alpha |00\rangle + \beta |10\rangle$.


**Goal:**  Change the two-qubit state to $\alpha |00\rangle + \beta |11\rangle$.

> Note that unless the starting state of the first qubit was $|0\rangle$ or $|1\rangle$,
> the resulting two-qubit state can not be represented as a tensor product
> of the states of individual qubits any longer; thus the qubits become entangled.

In [5]:
%kata T201_TwoQubitGate1

operation TwoQubitGate1 (qs : Qubit[]) : Unit is Adj+Ctl {
    CNOT(qs[0], qs[1]);
}

The starting state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0.8660254037844386 + 0𝑖
|11⟩	0 + 0𝑖

The desired state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.8660254037844386 + 0𝑖

The actual state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0 + 0𝑖
|10⟩	0 + 0𝑖
|11⟩	0.8660254037844386 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.1.-Two-qubit-gate---1).*

### Task 2.2. Two-qubit gate - 2

**Input:** Two unentangled qubits (stored in an array of length 2) in state $|+\rangle \otimes |+\rangle = \frac{1}{2} \big( |00\rangle + |01\rangle + |10\rangle {\color{blue}+} |11\rangle \big)$.


**Goal:**  Change the two-qubit state to $\frac{1}{2} \big( |00\rangle + |01\rangle + |10\rangle {\color{red}-} |11\rangle \big)$.

> Note that while the starting state can be represented as a tensor product of single-qubit states,
> the resulting two-qubit state can not be represented in such a way.

In [6]:
%kata T202_TwoQubitGate2

operation TwoQubitGate2 (qs : Qubit[]) : Unit is Adj+Ctl {
    Controlled Z([qs[0]], qs[1]);
}

The starting state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0.5000000000000001 + 0𝑖
|10⟩	0.5000000000000001 + 0𝑖
|11⟩	0.5000000000000001 + 0𝑖

The desired state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0.5000000000000001 + 0𝑖
|10⟩	0.5000000000000001 + 0𝑖
|11⟩	-0.5000000000000001 + 0𝑖

The actual state:


|00⟩	0.5000000000000001 + 0𝑖
|01⟩	0.5000000000000001 + 0𝑖
|10⟩	0.5000000000000001 + 0𝑖
|11⟩	-0.5000000000000001 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.2.-Two-qubit-gate---2).*

### Task 2.3. Two-qubit gate - 3

**Input:** Two qubits (stored in an array of length 2) in an arbitrary two-qubit state $\alpha |00\rangle + {\color{blue}\beta} |01\rangle + {\color{blue}\gamma} |10\rangle + \delta |11\rangle$.


**Goal:**  Change the two-qubit state to $\alpha |00\rangle + {\color{red}\gamma} |01\rangle + {\color{red}\beta} |10\rangle + \delta |11\rangle$.

> This task can be solved using one intrinsic gate; as an exercise, try to express the solution using several (possibly controlled) Pauli gates.

In [7]:
%kata T203_TwoQubitGate3

operation TwoQubitGate3 (qs : Qubit[]) : Unit is Adj+Ctl {
    SWAP(qs[0], qs[1]);
}

The starting state:


|00⟩	0.810243497447223 + 0𝑖
|01⟩	-0.515201372485301 + 0𝑖
|10⟩	-0.23578587428637512 + 0𝑖
|11⟩	0.14992678920314292 + 0𝑖

The desired state:


|00⟩	0.810243497447223 + 0𝑖
|01⟩	-0.23578587428637512 + 0𝑖
|10⟩	-0.515201372485301 + 0𝑖
|11⟩	0.14992678920314292 + 0𝑖

The actual state:


|00⟩	0.810243497447223 + 0𝑖
|01⟩	-0.23578587428637512 + 0𝑖
|10⟩	-0.515201372485301 + 0𝑖
|11⟩	0.14992678920314292 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.3.-Two-qubit-gate---3).*

### Task 2.4. Two-qubit gate - 4

**Input:** Two qubits (stored in an array of length 2) in an arbitrary two-qubit state ${\color{blue}\alpha} |00\rangle + {\color{blue}\beta} |01\rangle + \gamma |10\rangle + \delta |11\rangle$.


**Goal:**  Change the two-qubit state to ${\color{red}\beta} |00\rangle + {\color{red}\alpha} |01\rangle + \gamma |10\rangle + \delta |11\rangle$.

> This task can be solved using one library function; as an exercise, try to express the solution using several (possibly controlled) Pauli gates.  

> [ControlledOnInt function](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.canon.controlledonint) generates a controlled variant of the given gate, which is applied when the control register is in a state corresponding to a non-negative integer. For example,
  * `ControlledOnInt(0, H)([qs[0]], qs[1])` applies the Hadamard gate to the `qs[1]` qubit when the control qubit `qs[0]` is in the $|0\rangle$ state.  
  * `ControlledOnInt(1, X)([qs[0]], qs[1])` applies the X gate to the `qs[1]` qubit when the control qubit `qs[0]` is in the $|1\rangle$ state (equivalent to `CNOT(qs[0], qs[1])`).
>
> Notice that the `ControlledOnInt` function requires the control qubit(s) to be passed as an array. This function generates a gate controlled by multiple qubits. The argument gate is applied if the control register is in the basis state corresponding to the specified non-negative integer. The little-endian binary representation of this integer defines a bit mask, which is compared with the control register.
>
> A similar function `ControlledOnBitString` is introduced in the [Multi-Qubit Gates tutorial](../tutorials/MultiQubitGates/MultiQubitGates.ipynb#Other-Types-of-Controlled-Gates).

In [8]:
%kata T204_TwoQubitGate4

operation TwoQubitGate4 (qs : Qubit[]) : Unit is Adj+Ctl {
    X(qs[1]);
    CNOT(qs[0], qs[1]);
}

The starting state:


|00⟩	0.810243497447223 + 0𝑖
|01⟩	-0.515201372485301 + 0𝑖
|10⟩	-0.23578587428637512 + 0𝑖
|11⟩	0.14992678920314292 + 0𝑖

The desired state:


|00⟩	-0.515201372485301 + 0𝑖
|01⟩	0.810243497447223 + 0𝑖
|10⟩	-0.23578587428637512 + 0𝑖
|11⟩	0.14992678920314292 + 0𝑖

The actual state:


|00⟩	0.515201372485301 + 0𝑖
|01⟩	-0.810243497447223 + 0𝑖
|10⟩	0.23578587428637512 + 0𝑖
|11⟩	-0.14992678920314292 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.4.-Two-qubit-gate---4).*

### Task 2.5. Toffoli gate

**Input:** Three qubits (stored in an array of length 3) in an arbitrary three-qubit state 
$\alpha |000\rangle + \beta |001\rangle + \gamma |010\rangle + \delta |011\rangle + \epsilon |100\rangle + \zeta|101\rangle + {\color{blue}\eta}|110\rangle + {\color{blue}\theta}|111\rangle$.

**Goal:** Flip the state of the third qubit if the state of the first two is $|11\rangle$, i.e., change the three-qubit state to $\alpha |000\rangle + \beta |001\rangle + \gamma |010\rangle + \delta |011\rangle + \epsilon |100\rangle + \zeta|101\rangle + {\color{red}\theta}|110\rangle + {\color{red}\eta}|111\rangle$.

In [9]:
%kata T205_ToffoliGate

operation ToffoliGate (qs : Qubit[]) : Unit is Adj+Ctl {
    CCNOT(qs[0], qs[1], qs[2]);
}

The starting state:


|000⟩	0.5350173191105211 + 0𝑖
|001⟩	-0.6084825333625437 + 0𝑖
|010⟩	-0.34019607436232613 + 0𝑖
|011⟩	0.386909660255725 + 0𝑖
|100⟩	-0.15569335235923173 + 0𝑖
|101⟩	0.1770721845579774 + 0𝑖
|110⟩	0.09899916392422344 + 0𝑖
|111⟩	-0.11259310664098576 + 0𝑖

The desired state:


|000⟩	0.5350173191105211 + 0𝑖
|001⟩	-0.6084825333625437 + 0𝑖
|010⟩	-0.34019607436232613 + 0𝑖
|011⟩	0.386909660255725 + 0𝑖
|100⟩	-0.15569335235923173 + 0𝑖
|101⟩	0.1770721845579774 + 0𝑖
|110⟩	-0.11259310664098576 + 0𝑖
|111⟩	0.09899916392422344 + 0𝑖

The actual state:


|000⟩	0.5350173191105211 + 0𝑖
|001⟩	-0.6084825333625437 + 0𝑖
|010⟩	-0.34019607436232613 + 0𝑖
|011⟩	0.386909660255725 + 0𝑖
|100⟩	-0.15569335235923173 + 0𝑖
|101⟩	0.1770721845579774 + 0𝑖
|110⟩	-0.11259310664098576 + 0𝑖
|111⟩	0.09899916392422344 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.5.-Toffoli-gate).*

### Task 2.6. Fredkin gate

**Input:** Three qubits (stored in an array of length 3) in an arbitrary three-qubit state 
$\alpha |000\rangle + \beta |001\rangle + \gamma |010\rangle + \delta |011\rangle + \epsilon |100\rangle + {\color{blue}\zeta}|101\rangle + {\color{blue}\eta}|110\rangle + \theta|111\rangle$.

**Goal:** Swap the states of second and third qubit if and only if the state of the first qubit is $|1\rangle$, i.e., change the three-qubit state to $\alpha |000\rangle + \beta |001\rangle + \gamma |010\rangle + \delta |011\rangle + \epsilon |100\rangle + {\color{red}\eta}|101\rangle + {\color{red}\zeta}|110\rangle + \theta|111\rangle$.

In [10]:
%kata T206_FredkinGate

operation FredkinGate (qs : Qubit[]) : Unit is Adj+Ctl {
    Controlled SWAP([qs[0]], (qs[1], qs[2]));
}

The starting state:


|000⟩	0.5350173191105211 + 0𝑖
|001⟩	-0.6084825333625437 + 0𝑖
|010⟩	-0.34019607436232613 + 0𝑖
|011⟩	0.386909660255725 + 0𝑖
|100⟩	-0.15569335235923173 + 0𝑖
|101⟩	0.1770721845579774 + 0𝑖
|110⟩	0.09899916392422344 + 0𝑖
|111⟩	-0.11259310664098576 + 0𝑖

The desired state:


|000⟩	0.5350173191105211 + 0𝑖
|001⟩	-0.6084825333625437 + 0𝑖
|010⟩	-0.34019607436232613 + 0𝑖
|011⟩	0.386909660255725 + 0𝑖
|100⟩	-0.15569335235923173 + 0𝑖
|101⟩	0.09899916392422344 + 0𝑖
|110⟩	0.1770721845579774 + 0𝑖
|111⟩	-0.11259310664098576 + 0𝑖

The actual state:


|000⟩	-0.5350173191105211 + 0𝑖
|001⟩	0.6084825333625437 + 0𝑖
|010⟩	0.34019607436232613 + 0𝑖
|011⟩	-0.386909660255725 + 0𝑖
|100⟩	0.15569335235923173 + 0𝑖
|101⟩	-0.09899916392422344 + 0𝑖
|110⟩	-0.1770721845579774 + 0𝑖
|111⟩	0.11259310664098576 + 0𝑖

Success!

*Can't come up with a solution? See the explained solution in the [Basic Gates Workbook](./Workbook_BasicGates.ipynb#Task-2.6.-Fredkin-gate).*